name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - backend
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Run a test command
        run: echo "Running CI pipeline..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy step
        run: echo "Deploying application..."
